# Generated by Django 3.2.16 on 2024-01-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_venda_valor_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='valor_pago',
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
