# Generated by Django 3.2.16 on 2024-01-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_auto_20240117_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
