# Generated by Django 3.2.16 on 2024-01-17 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20240117_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
